openapi: 3.0.0
info:
  title: Learning Management System API
  description: API for managing courses, students, and enrollments in a learning management system.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /courses:
    get:
      summary: Get all courses
      responses:
        '200':
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
    post:
      summary: Create a new course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '201':
          description: Course created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'

  /courses/{courseId}:
    get:
      summary: Get course by ID
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'

  /students:
    get:
      summary: Get all students
      responses:
        '200':
          description: A list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

  /enrollments:
    post:
      summary: Enroll a student in a course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '201':
          description: Enrollment created successfully

components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
    Student:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    Enrollment:
      type: object
      properties:
        courseId:
          type: string
        studentId:
          type: string
